### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by pacisauctor** [pacisauctor/academy-control-system#3]
- [x] CAula y CEdificio @junietza  
- [x] CMatricula y CEstudiante @stevenEspinoza2224 
- [x] CCurso y CPrograma @Callme-Red 
- [x] CTurno y CTipoProfesor @pacisauctor 
- [x] CProfesor y CReglaNegocio @JEBenitezSan
